// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Verifies that a photo contains a human face.
 *
 * - verifyFaceAttendance - A function that verifies if a human face is present in an image.
 * - VerifyFaceAttendanceInput - The input type for the verifyFaceAttendance function.
 * - VerifyFaceAttendanceOutput - The return type for the verifyFaceAttendance function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const VerifyFaceAttendanceInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to be checked for faces, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type VerifyFaceAttendanceInput = z.infer<typeof VerifyFaceAttendanceInputSchema>;

const VerifyFaceAttendanceOutputSchema = z.object({
  faceDetected: z.boolean().describe('Whether a face was detected in the image.'),
});
export type VerifyFaceAttendanceOutput = z.infer<typeof VerifyFaceAttendanceOutputSchema>;

export async function verifyFaceAttendance(input: VerifyFaceAttendanceInput): Promise<VerifyFaceAttendanceOutput> {
  return verifyFaceAttendanceFlow(input);
}

const verifyFaceAttendancePrompt = ai.definePrompt({
  name: 'verifyFaceAttendancePrompt',
  input: {schema: VerifyFaceAttendanceInputSchema},
  output: {schema: VerifyFaceAttendanceOutputSchema},
  prompt: `You are an AI that analyzes images to detect human faces.

  Analyze the following image and determine if it contains a human face.  If a human face is present, set faceDetected to true.  If no face is present, set faceDetected to false.

  Image: {{media url=photoDataUri}}
  `,
});

const verifyFaceAttendanceFlow = ai.defineFlow(
  {
    name: 'verifyFaceAttendanceFlow',
    inputSchema: VerifyFaceAttendanceInputSchema,
    outputSchema: VerifyFaceAttendanceOutputSchema,
  },
  async input => {
    const {output} = await verifyFaceAttendancePrompt(input);
    return output!;
  }
);
